/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import conexiones.conexionOracle;
import conexiones.conexionPostgre;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import java.sql.Connection;

/**
 *
 * @author djbrz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Replicacion = new javax.swing.JDialog();
        Btn_agregar_replica = new javax.swing.JButton();
        Btn_eliminar_replica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_tablas_destino = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_tablas_origen = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        Btn_guardar_Tablas = new javax.swing.JButton();
        Btn_Cancelar_tablas = new javax.swing.JButton();
        baseDatos = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton27 = new javax.swing.JButton();
        bitacora = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        Tabla_campus = new javax.swing.JTable();
        jButton24 = new javax.swing.JButton();
        label5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        Conexion = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        instancia_base_origen = new javax.swing.JTextField();
        puerto_base_origen = new javax.swing.JTextField();
        nombre_base_origen = new javax.swing.JTextField();
        usuario_base_origen = new javax.swing.JTextField();
        password_base_origen = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        instancia_base_destino = new javax.swing.JTextField();
        nombre_base_destino = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        puerto_base_destino = new javax.swing.JTextField();
        usuario_base_destino = new javax.swing.JTextField();
        password_base_destino = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        Btn_agregar_replica.setText(">>");
        Btn_agregar_replica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_agregar_replicaMouseClicked(evt);
            }
        });

        Btn_eliminar_replica.setText("<<");

        jLabel1.setText("Sin Replicar");

        jLabel2.setText("Replicando");

        lista_tablas_destino.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(lista_tablas_destino);

        Lista_tablas_origen.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(Lista_tablas_origen);

        jLabel3.setText("Tablas BD Origen");

        Btn_guardar_Tablas.setText("Guardar");

        Btn_Cancelar_tablas.setText("Cancelar");
        Btn_Cancelar_tablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_Cancelar_tablasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ReplicacionLayout = new javax.swing.GroupLayout(Replicacion.getContentPane());
        Replicacion.getContentPane().setLayout(ReplicacionLayout);
        ReplicacionLayout.setHorizontalGroup(
            ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReplicacionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_eliminar_replica)
                    .addComponent(Btn_agregar_replica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
            .addGroup(ReplicacionLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Btn_guardar_Tablas)
                .addGap(140, 140, 140)
                .addComponent(Btn_Cancelar_tablas)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ReplicacionLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(119, 119, 119)
                .addComponent(jLabel2)
                .addGap(96, 96, 96))
        );
        ReplicacionLayout.setVerticalGroup(
            ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReplicacionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReplicacionLayout.createSequentialGroup()
                        .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReplicacionLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(Btn_agregar_replica)
                                .addGap(72, 72, 72)
                                .addComponent(Btn_eliminar_replica))
                            .addGroup(ReplicacionLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_guardar_Tablas)
                    .addComponent(Btn_Cancelar_tablas))
                .addGap(55, 55, 55))
        );

        baseDatos.setTitle("Hacia la bitácora...");
        baseDatos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setToolTipText("Hacia la bitácora...");

        jButton27.setText("Ver bitacora POSTGRESQL");
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton27MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jButton27)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jButton27)
                .addGap(87, 87, 87))
        );

        baseDatos.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 180));

        bitacora.setTitle("Bitácora");

        Tabla_campus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tabla Afectada", "Operacion realizada", "Llave primaria", "Datos "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(Tabla_campus);

        jButton24.setText("Cerrar");
        jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton24MouseClicked(evt);
            }
        });

        label5.setText("Bitácora POSTGRESQL");

        jButton3.setText("Listar");

        javax.swing.GroupLayout bitacoraLayout = new javax.swing.GroupLayout(bitacora.getContentPane());
        bitacora.getContentPane().setLayout(bitacoraLayout);
        bitacoraLayout.setHorizontalGroup(
            bitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bitacoraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bitacoraLayout.createSequentialGroup()
                        .addComponent(label5)
                        .addGap(335, 335, 335))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bitacoraLayout.createSequentialGroup()
                        .addComponent(jButton24)
                        .addContainerGap())))
            .addGroup(bitacoraLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(bitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        bitacoraLayout.setVerticalGroup(
            bitacoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bitacoraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label5)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(3, 3, 3)
                .addComponent(jButton24)
                .addContainerGap())
        );

        Conexion.setTitle("Comprobar Conexion");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Base de datos Origen (Postgre)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Base de datos Destino (Oracle)");

        jLabel6.setText("Nombre Instancia:");

        jLabel7.setText("Nombre base de datos:");

        jLabel8.setText("Puerto:");

        jLabel9.setText("Nombre de usuario:");

        jLabel10.setText("Password: ");

        jLabel11.setText("Nombre Instancia:");

        jLabel12.setText("Nombre base de datos:");

        jLabel13.setText("Puerto:");

        jLabel14.setText("Nombre de usuario:");

        jLabel15.setText("Password: ");

        jButton4.setText("Probar Conexion");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Probar Conexion");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Reailzar sincronizacion");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ConexionLayout = new javax.swing.GroupLayout(Conexion.getContentPane());
        Conexion.getContentPane().setLayout(ConexionLayout);
        ConexionLayout.setHorizontalGroup(
            ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConexionLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(82, 82, 82))
            .addGroup(ConexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(ConexionLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ConexionLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usuario_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ConexionLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(instancia_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ConexionLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(puerto_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ConexionLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nombre_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConexionLayout.createSequentialGroup()
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ConexionLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(password_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConexionLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usuario_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConexionLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(instancia_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConexionLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(puerto_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConexionLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombre_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConexionLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(51, 51, 51))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConexionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(213, 213, 213))
        );
        ConexionLayout.setVerticalGroup(
            ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConexionLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConexionLayout.createSequentialGroup()
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(instancia_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nombre_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(puerto_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(usuario_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password_base_origen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(ConexionLayout.createSequentialGroup()
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(instancia_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nombre_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(puerto_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(usuario_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password_base_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addGap(32, 32, 32)
                .addGroup(ConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");

        jButton1.setText("Manejo de las bases");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Manejo de las tablas");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        Conexion.setModal(true);
        Conexion.pack();
        Conexion.setLocationRelativeTo(this);
        Conexion.setVisible(true);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        baseDatos.setModal(true);
        baseDatos.pack();
        baseDatos.setLocationRelativeTo(this);
        baseDatos.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseClicked
        // TODO add your handling code here:
        bitacora.dispose();
    }//GEN-LAST:event_jButton24MouseClicked

    private void Btn_Cancelar_tablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Cancelar_tablasMouseClicked
        // TODO add your handling code here:
        Replicacion.dispose();
    }//GEN-LAST:event_Btn_Cancelar_tablasMouseClicked

    private void jButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseClicked
        // TODO add your handling code here:
        bitacora.setModal(true);
        bitacora.pack();
        bitacora.setLocationRelativeTo(this);
        bitacora.setVisible(true);
    }//GEN-LAST:event_jButton27MouseClicked

    private void Btn_agregar_replicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_agregar_replicaMouseClicked
        // TODO add your handling code here:
        if(Lista_tablas_origen.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento de la lista para replicar", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            DefaultListModel model=(DefaultListModel)Lista_tablas_origen.getModel();
            String tabla="";
            tabla=(String)model.getElementAt(Lista_tablas_origen.getSelectedIndex());
            DefaultListModel modelo=(DefaultListModel)lista_tablas_destino.getModel();
            
            boolean flag=false;
            for (int i = 0; i <modelo.getSize(); i++) {
                if(tabla.equalsIgnoreCase((String)modelo.getElementAt(i))){
                    flag=true;
                }
            }
            if(flag==false){
                modelo.addElement(tabla);
               lista_tablas_destino.setModel(modelo);
            }
            else{
                JOptionPane.showMessageDialog(this, "Ya agrego esta tabla a su base de datos de destino", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_Btn_agregar_replicaMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        String instancia="", usuario="", password="", nombre="", puerto="";
        instancia=instancia_base_origen.getText();
        usuario=usuario_base_origen.getText();
        password=password_base_origen.getText();
        nombre=nombre_base_origen.getText();
        puerto=puerto_base_origen.getText();
        instancia="jdbc:postgresql://"+instancia+":"+puerto+"/"+nombre;
        try {
            Connection c=conexionPostgre.getConnection(usuario, password, instancia);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo=(DefaultListModel)Lista_tablas_origen.getModel();
        modelo.addElement("Alumno");
        modelo.addElement("Aula");
        modelo.addElement("Campus");
        modelo.addElement("Docente");
        modelo.addElement("Edificio");
        modelo.addElement("Facultdad");
        Lista_tablas_origen.setModel(modelo);
        Replicacion.setModal(true);
        Replicacion.pack();
        Replicacion.setLocationRelativeTo(this);
        Replicacion.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String instancia="", usuario="", password="", nombre="", puerto="";
        instancia=instancia_base_destino.getText();
        usuario=usuario_base_destino.getText();
        password=password_base_destino.getText();
        nombre=nombre_base_destino.getText();
        puerto=puerto_base_destino.getText();
        instancia="jdbc:oracle:thin:@"+instancia+":"+puerto+":"+nombre;
        try {
            Connection con =conexionOracle.getConnection(usuario,password,instancia);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("WINDOWS".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cancelar_tablas;
    private javax.swing.JButton Btn_agregar_replica;
    private javax.swing.JButton Btn_eliminar_replica;
    private javax.swing.JButton Btn_guardar_Tablas;
    private javax.swing.JDialog Conexion;
    private javax.swing.JList<String> Lista_tablas_origen;
    private javax.swing.JDialog Replicacion;
    private javax.swing.JTable Tabla_campus;
    private javax.swing.JDialog baseDatos;
    private javax.swing.JDialog bitacora;
    private javax.swing.JTextField instancia_base_destino;
    private javax.swing.JTextField instancia_base_origen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel label5;
    private javax.swing.JList<String> lista_tablas_destino;
    private javax.swing.JTextField nombre_base_destino;
    private javax.swing.JTextField nombre_base_origen;
    private javax.swing.JTextField password_base_destino;
    private javax.swing.JTextField password_base_origen;
    private javax.swing.JTextField puerto_base_destino;
    private javax.swing.JTextField puerto_base_origen;
    private javax.swing.JTextField usuario_base_destino;
    private javax.swing.JTextField usuario_base_origen;
    // End of variables declaration//GEN-END:variables

}
/*
           1 alumno: nombre apellido id cuenta carrera telefono fechaingres
           2 docente nombre ,apellidos, facultad, id, cuenta ,profe, años ,genero, doble
           3 facultad nombre añocreacion cantidad docentes, cantidad alumnos, cantidad de clases
           4 aula numero edificio, datashow ,pizarra ,capacidad, aire ,compu, internet
           5 edificio numero_edi, nombre_edi, numero_pisos, cantidad_aulas, año_fundacion, cantidad_baños
           6 campus nombre, ciudad ,cantidad_edificios, cantidad_almunos, año recotr
 */
