/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2_teoria2;

/**
 *
 * @author djbrz
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Replicacion = new javax.swing.JDialog();
        Btn_agregar_replica = new javax.swing.JButton();
        Btn_eliminar_replica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista_tablas_destino = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_tablas_origen = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        Btn_guardar_Tablas = new javax.swing.JButton();
        Btn_Cancelar_tablas = new javax.swing.JButton();
        Conexiones = new javax.swing.JDialog();
        Creacion_tablas = new javax.swing.JDialog();
        Btn_crear = new javax.swing.JButton();
        Btn_modificar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Admin = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        Btn_agregar_replica.setText(">>");

        Btn_eliminar_replica.setText("<<");

        jLabel1.setText("Sin Replicar");

        jLabel2.setText("Replicando");

        jScrollPane1.setViewportView(lista_tablas_destino);

        jScrollPane2.setViewportView(Lista_tablas_origen);

        jLabel3.setText("Tablas BD Origen");

        Btn_guardar_Tablas.setText("Guardar");

        Btn_Cancelar_tablas.setText("Cancelar");

        javax.swing.GroupLayout ReplicacionLayout = new javax.swing.GroupLayout(Replicacion.getContentPane());
        Replicacion.getContentPane().setLayout(ReplicacionLayout);
        ReplicacionLayout.setHorizontalGroup(
            ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReplicacionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReplicacionLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn_eliminar_replica)
                            .addComponent(Btn_agregar_replica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(ReplicacionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2)
                        .addGap(121, 121, 121))))
            .addGroup(ReplicacionLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(Btn_guardar_Tablas)
                .addGap(140, 140, 140)
                .addComponent(Btn_Cancelar_tablas)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ReplicacionLayout.setVerticalGroup(
            ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReplicacionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReplicacionLayout.createSequentialGroup()
                        .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ReplicacionLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(Btn_agregar_replica)
                                .addGap(72, 72, 72)
                                .addComponent(Btn_eliminar_replica))
                            .addGroup(ReplicacionLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(ReplicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_guardar_Tablas)
                    .addComponent(Btn_Cancelar_tablas))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout ConexionesLayout = new javax.swing.GroupLayout(Conexiones.getContentPane());
        Conexiones.getContentPane().setLayout(ConexionesLayout);
        ConexionesLayout.setHorizontalGroup(
            ConexionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );
        ConexionesLayout.setVerticalGroup(
            ConexionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        Creacion_tablas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_crear.setText("Crear Tabla");
        Creacion_tablas.getContentPane().add(Btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 172, -1, -1));

        Btn_modificar.setText("Modificar Tabla");
        Creacion_tablas.getContentPane().add(Btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 172, -1, -1));

        Btn_eliminar.setText("Eliminar Tabla");
        Creacion_tablas.getContentPane().add(Btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 172, -1, -1));

        Tabla_Admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Tabla_Admin);

        Creacion_tablas.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 375, 131));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("manejo de las bases");

        jButton2.setText("manejo de las tablas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(34, 34, 34)
                .addComponent(jButton2)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Cancelar_tablas;
    private javax.swing.JButton Btn_agregar_replica;
    private javax.swing.JButton Btn_crear;
    private javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_eliminar_replica;
    private javax.swing.JButton Btn_guardar_Tablas;
    private javax.swing.JButton Btn_modificar;
    private javax.swing.JDialog Conexiones;
    private javax.swing.JDialog Creacion_tablas;
    private javax.swing.JList<String> Lista_tablas_origen;
    private javax.swing.JDialog Replicacion;
    private javax.swing.JTable Tabla_Admin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lista_tablas_destino;
    // End of variables declaration//GEN-END:variables
}
